### ISSUE TITLE
ontv sync error

### ISSUE THREAD

**Issue by marteaurouge** [udoprog/ontv#1]
Getting this (i already set the api key in ~ .ontv/db)

```
Backed up library directory to: /home/bob/.ontv-backups/2016_02_17_0
Migrating database version 1
Traceback (most recent call last):
  File "/usr/local/bin/ontv", line 13, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/ontv/__init__.py", line 368, in main
    migration_check(ns)
  File "/usr/local/lib/python2.7/dist-packages/ontv/__init__.py", line 323, in migration_check
    migration(ns)
  File "/usr/local/lib/python2.7/dist-packages/ontv/__init__.py", line 259, in migrate_1
    del db["series"]
  File "/usr/local/lib/python2.7/dist-packages/ontv/database.py", line 312, in __delitem__
    dict.__delitem__(self, key)
KeyError: 'series'

```

**Comment by udoprog** [comment]
complete rewrite in progress, so sorry about being late :D
